name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: studyplanner
          cache: true

      - name: Install rcmdcheck
        shell: Rscript {0}
        run: install.packages("rcmdcheck")

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: studyplanner
          upload-snapshots: true
