name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install deps (local pkg + covr + testthat + xml2)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            local::./studyplanner
            any::covr
            any::testthat
            any::xml2
          cache: true

      - name: Generate coverage XML
        shell: Rscript {0}
        run: |
          setwd("studyplanner")
          cov <- covr::package_coverage(path = ".", quiet = FALSE)
          cat("Percent coverage:", covr::percent_coverage(cov), "%\n")
          covr::to_cobertura(cov, file = "coverage.xml")

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: studyplanner/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
